name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

# Sets permissions for deployment
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # Fetch full history for Git LFS
        fetch-depth: 0
        lfs: true
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Checkout LFS objects
      run: git lfs checkout
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Configure Git LFS for deployment
      run: |
        cd build
        git init
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git lfs install
        git lfs track "unity-build/*.data"
        git lfs track "unity-build/*.wasm"
        git add .gitattributes
        git add .
        git commit -m "Deploy to GitHub Pages"
        
    - name: Deploy to GitHub Pages
      run: |
        cd build
        git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git push -f origin HEAD:gh-pages